### ISSUE TITLE
Create a GUI for Camera Inferno

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/cameraInferno-maya#1]
Configuring the Camera Inferno node is not intuitive using the Maya Attribute Editor, a GUI should be created to help the process of creating the node (with presets) for users to use.

**Comment by satishgoda** [comment]
Great tool. Thank you for creating it and sharing it.

I have been testing with Maya 2020 and seems to be working fine so far.

**Comment by david-cattermole** [comment]
Creating a Qt UI for this tool seems to be overkill for the gain it will bring.

I have added Attribute Editor Templates in the `v0.3.0` version, which helps a lot.
