### ISSUE TITLE
Add Maya Module for Easier Installation

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/cameraInferno-maya#6]
Use Maya "Modules" to simplify installation of the scripts and plug-in.

Currently users must install multiple files. For example here is the current installation steps:
```
The installation is basic and manual, simply copy the Python and MEL files to your home directory's maya folder.

    Copy ./plug-ins/dcCameraInferno.py into the directory ${HOME}/maya/<maya version>/plug-ins.
    Copy ./plug-ins/dcVelocity.py into the directory ${HOME}/maya/<maya version>/plug-ins.
    Copy ./scripts/AEdcCameraInfernoTemplate.mel into the directory ${HOME}/maya/<maya version>/scripts.
    Copy ./python/dcCameraInferno into the directory ${HOME}/maya/<maya version>/scripts.
```

This is a lot of copying of individual files. Ideally we would use a similar system to mmSolver with a .mod file and a directory saved into `${HOME}/maya/<maya version>/modules`. See [this](https://github.com/david-cattermole/mayaMatchMoveSolver/blob/master/INSTALL.md#install-maya-module) for details.

Helpful documentation pages for the feature:
https://around-the-corner.typepad.com/adn/2012/07/distributing-files-on-maya-maya-modules.html
https://around-the-corner.typepad.com/adn/2013/04/distributing-plug-insfiles-on-maya-and-3ds-max.html
https://help.autodesk.com/view/MAYAUL/2017/ENU/?guid=__files_GUID_CB76E356_753B_4837_8C5B_3296C14872CA_htm

**Comment by satishgoda** [comment]
This is a great idea :) 

I am also deploying all our tools for the previs team as a maya Module itself.

**Comment by david-cattermole** [comment]
This is now done and released here; https://github.com/david-cattermole/cameraInferno-maya/releases/tag/v0.3.0
