### ISSUE TITLE
MAYA 2022

### ISSUE THREAD

**Issue by sirpiltrafus** [david-cattermole/cameraInferno-maya#8]
Hi,
I'll like to use this as a replacement for the old SONY SpReticle I've been using so far.
We are moving to Maya 2022 soon and realized this plugin doesn't work. It loads but it wont display text or dots. only the black aspect ratio bars work.

I guess it needs to be updated to python3 or something?
Just wanted to know if you have plans for Maya 2022.
Thanks for sharing this  amazing work.

**Comment by david-cattermole** [comment]
Hello @sirpiltrafus

You are correct, it has not been tested on Maya 2022, yet. 

Python 3 is a possible reason for the issue, but there might be other problems such as with Parallel Evaluation.

I won't have time to look at this issue for about 2 weeks.

Also, can you confirm you are using the latest pre-release plug-in, v0.3.0? If not, you could try updating and seeing if problems still persist.

Thanks for reporting this!

David

**Comment by sirpiltrafus** [comment]
Yes. I'm using v.0.3.0

I get this error last time I tried (dx11 vp2)
// Error: TypeError: file C:/Users/Joan/Documents/maya/2022/modules/cameraInferno-0.3.0/plug-ins/dcCameraInferno.py line 2414: object of type 'zip' has no len() //

**Comment by jomaro110** [comment]
> Yes. I'm using v.0.3.0
> 
> I get this error last time I tried (dx11 vp2) // Error: TypeError: file C:/Users/Joan/Documents/maya/2022/modules/cameraInferno-0.3.0/plug-ins/dcCameraInferno.py line 2414: object of type 'zip' has no len() //

Hi sirpiltrafus,
Did you managed to use the script with Maya 2022 yet?

**Comment by david-cattermole** [comment]
Hello @jomaro110 and @sirpiltrafus,

I have not had time to work on this project, and I'm not sure I'll have time soon.

If you have the ability or know someone that can port this to Python 3 and Maya 2022 and would be willing to contribute back to this open source project please do help out if you can.

David

**Comment by Eiken** [comment]
Added a merge request with 0.4.0 for supporting 2022+ that should also be compatible with older versions

**Comment by david-cattermole** [comment]
Thanks @Eiken! I've released your change as v0.4.1 for people to download:
https://github.com/david-cattermole/cameraInferno-maya/releases/tag/v0.4.1
